services:
  tourhysm-ai:
    container_name: tourhysm-ai
    build: .
    command: sh -c """
      alembic upgrade head &&
      uvicorn src.app:app --host 0.0.0.0 --port 9000
      """
    ports:
      - "9000:9000"
    env_file:
      - .env
    depends_on: # Start app after database and redis is ready
      - tourhysm-ai-db
      - tourhysm-ai-redis

  tourhysm-ai-optimizer:
    container_name: tourhysm-ai-optimizer
    build: .
    command: celery -A src.optimizer._celery worker --loglevel=info
    env_file:
      - .env
    depends_on: # Start optimizer after database and redis is ready
      - tourhysm-ai-db
      - tourhysm-ai-redis

  tourhysm-ai-db:
    container_name: tourhysm-ai-db
    image: postgres:15
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes: # persist data
      - tourhysm-ai-data:/var/lib/postgresql/data

  tourhysm-ai-redis:
    container_name: tourhysm-ai-redis
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes: # persist data
      - tourhysm-ai-cache:/data


volumes:
  tourhysm-ai-data:
  tourhysm-ai-cache:
